jobs:
- job: check_formatting
  displayName: Check formatting
  pool:
    vmImage: ubuntu-16.04
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        $HOME/.cargo/bin/rustup component add rustfmt
      displayName: Install stable Rust
    - script: |
        $HOME/.cargo/bin/cargo fmt -- --check
      displayName: Run rustfmt

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      minimum_supported_version:
        rustup_toolchain: 1.31.0
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install rust
    - script: |
          rustc -Vv
          cargo -V
      displayName: Query rust and cargo versions
    - script: _build/cargo-make.sh "0.16.8" "x86_64-unknown-linux-musl"
      displayName: Install cargo-make binary
    - script: cargo make ci-flow
      displayName: CI flow
